### ISSUE TITLE
Missing Source file

### ISSUE THREAD

**Issue by hardcoat** [mikeduglas/PostgreSQL-for-Clarion#1]
The source file "libpq.clw" is missing. This file is linked in your CLASS's.

**Comment by mikeduglas** [comment]
It is for sale.

**Comment by mriffey** [comment]
Price?

**Comment by mikeduglas** [comment]
$200

**Comment by mriffey** [comment]
Thanks Mike. I haven’t tried to test it yet, but I will. Does it support blobs?

Mark

**Comment by mikeduglas** [comment]
yes it does.

**Comment by mriffey** [comment]
I was thinking Id be able to test it, but that doesnt appear to be the case. How do I pay?
