### ISSUE TITLE
How to pay?

### ISSUE THREAD

**Issue by mriffey** [mikeduglas/PostgreSQL-for-Clarion#2]
I was thinking Id be able to test it, but that doesnt appear to be the case. How do I pay?

**Comment by mikeduglas** [comment]
Mark,
I can send you full package to test.

**Comment by mikeduglas** [comment]
Mark,
I can send you full package to test.

**Comment by mriffey** [comment]
Please email details to pulledoutplum on gmail. Thanks:)
